### ISSUE TITLE
Copy examples, etc. from Scala universal recommender over to Java version

### ISSUE THREAD

**Issue by rhenwood39** [cbora/predictionio-template-java-universal-recommender#39]
We need to copy over
* docs
* data
* examples
* probably some json stuff

**Comment by rhenwood39** [comment]
Not necessarily. The stuff in docs, sure.

But I don't think all the stuff we have to copy over falls under documentation. E.g., some of the stuff in examples and data relate to integration testing.

I haven't really looked through the json stuff, but I don't know if that falls under documentation either.

**Comment by rhenwood39** [comment]
The data directory is just a bunch of data files and expected output files. So we should be able to copy them over without any adjustments.

**Comment by rhenwood39** [comment]
docs is just a single README. Skimming it over, I don't think there's much we need to do to it.

**Comment by rhenwood39** [comment]
From class today, it sounds like the ML team is going to handle this and try to get the included integration tests up and running. So I assigned it to you all.

**Comment by jk2227** [comment]
I copied over all the examples and data files from actionml repo

**Comment by rhenwood39** [comment]
Cool! Have you tried running any of the integration tests?
